print ("------------- Hands on 1 ---------------------------------------")
favoriteFoods=["Shrimp","Ice Cream","Apple Muffins","Sea Food Stirfry","Beef Enchiladas","Ham Cheese Potato Soup"]
print("Favorite Foods:", (favoriteFoods))
favoriteNumbers=["2","7","11","22","24","44"]
print("Favorite Numbers:", (favoriteNumbers))
favoriteMovies=["Aladin","Game of Thrones","Dragon Heart"]
print("Favorite Movies:", (favoriteMovies))
print("Combo List:", (favoriteFoods[0], favoriteFoods[-3], favoriteNumbers[1], favoriteNumbers[-3], favoriteMovies[0], favoriteMovies[-1]))
print("Last Food Item:", (favoriteFoods[-1]))
print("2nd 4th and 6th numbers:", (favoriteNumbers[1], favoriteNumbers[3], favoriteNumbers[5]))
print("All Movies:", (favoriteMovies))
print("First food, first number and first movie:",(favoriteFoods[0], favoriteNumbers[0], favoriteMovies[0]))

print ("------------- Hands on 2 ---------------------------------------")
favoriteMovies.append("How to Train Your Dragon")
print("Added Movie:",(favoriteMovies))
favoriteNumbers.insert(3,"222")
print("Added number at sub 3:",(favoriteNumbers))
favoriteFoods.insert(5,"Pork Steak")
print("Added food at sub 5:",(favoriteFoods))
del favoriteFoods[6]
print("Deleted food[6]:",(favoriteFoods))
removedNumber1= favoriteNumbers.pop()
print("Deleted last number:",(favoriteNumbers))
removedNumber2= favoriteNumbers.pop(2)
print("Deleted number at sub 2:",(favoriteNumbers))

print ("------------- Hands on 3 ---------------------------------------")
favoriteMovies.sort()
print("Sorted list:",(favoriteMovies))
favoriteFoods.sort()
print("Sorted list:",(favoriteFoods))
print("Temp sorted list:",sorted(favoriteNumbers))
print("Unsorted List:",(favoriteNumbers))
favoriteMovies.reverse()
print("Sorted in reverse:",(favoriteMovies))

print ("------------- Exercise 5-4 -------------------------------------")
invitedPeople=["Abraham Lincoln","Devin Patrick","Telsa McBride"]
print(f"Hello {invitedPeople[0]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[1]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[2]}, Would you be able to make it to dinner this Saturday?")

print ("------------- Exercise 5-5 -------------------------------------")
print(f"{invitedPeople[0]} is unable to make it to dinner.")
del invitedPeople[0]
invitedPeople.append("Grandpa Joe")
print(f"Hello {invitedPeople[0]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[1]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[2]}, Would you be able to make it to dinner this Saturday?")

print ("------------- Exercise 5-6 -------------------------------------")
print("I was able to find a larger table so we will be able to have more guests!")
invitedPeople.insert(0,"Grandma Sally")
invitedPeople.insert(2,"Kayla Lutke")
invitedPeople.append("Alex Lutke")
print("I am inviting",len(invitedPeople),"people to dinner.")
print(f"Hello {invitedPeople[0]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[1]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[2]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[3]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[4]}, Would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[5]}, Would you be able to make it to dinner this Saturday?")

print ("------------- Exercise 5-7 -------------------------------------")
print("I apologize, it turns out my table will not arrive in time and I will only be able to invite 2 people.")
print(f"I am sorry {invitedPeople[5]}, I cannot have you over for dinner this Saturday. Possibly next Saturday?")
invitedPeople.pop(5)
print(f"I am sorry {invitedPeople[0]}, I cannot have you over for dinner this Saturday. Possibly next Saturday?")
invitedPeople.pop(0)
print(f"I am sorry {invitedPeople[3]}, I cannot have you over for dinner this Saturday. Possibly next Saturday?")
invitedPeople.pop(3)
print(f"I am sorry {invitedPeople[1]}, I cannot have you over for dinner this Saturday. Possibly next Saturday?")
invitedPeople.pop(1)
print(f"Hello {invitedPeople[0]}, would you be able to make it to dinner this Saturday?")
print(f"Hello {invitedPeople[1]}, would you be able to make it to dinner this Saturday?")
del invitedPeople[1]
del invitedPeople[0]
print("Here is my revised guest list:",invitedPeople)